/**
 * Desktop Pet Online common message protocol
 * Client <-> Server message definitions
 */

module.exports = {
  LOGIN: 'LOGIN',
  WELCOME: 'WELCOME',
  USER_UPDATE: 'USER_UPDATE',

  ROOM_JOIN: 'ROOM_JOIN',
  ROOM_JOINED: 'ROOM_JOINED',
  ROOM_LEAVE: 'ROOM_LEAVE',
  ROOM_CREATE: 'ROOM_CREATE',
  ROOM_LIST: 'ROOM_LIST',
  ROOM_USERS: 'ROOM_USERS',

  CHAT: 'CHAT',

  PET_UPDATE: 'PET_UPDATE',
  PET_SYNC: 'PET_SYNC',

  HEARTBEAT: 'HEARTBEAT',
  HEARTBEAT_ACK: 'HEARTBEAT_ACK',

  LOGIN_OK: 'LOGIN_OK',
  ONLINE_LIST: 'ONLINE_LIST',

  ERROR: 'ERROR'
};
